#!/bin/bash

# Train all learnable models for temperature forecasting
# Usage: bash train_all_models.sh [seed]
#   seed: Optional random seed (default: random seed generated by Hydra)

set -e  # Exit on error

# ============================================================================
# Configuration
# ============================================================================
DATASET="temperature"
MODELS=("tcn" "rnn" "stgnn" "attn_longterm")
SEED="${1:-}"  # Accept seed as first argument, empty if not provided
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")

# Log directory structure
LOG_DIR="logs"
SUMMARY_DIR="${LOG_DIR}/summaries"
MODEL_DIR="${LOG_DIR}/models"

# Create log directories
mkdir -p "${SUMMARY_DIR}" "${MODEL_DIR}"

# Log file paths
if [ -n "$SEED" ]; then
    SUMMARY_LOG="${SUMMARY_DIR}/training_summary_seed${SEED}_${TIMESTAMP}.log"
else
    SUMMARY_LOG="${SUMMARY_DIR}/training_summary_${TIMESTAMP}.log"
fi

# ============================================================================
# Color definitions
# ============================================================================
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# ============================================================================
# Helper functions
# ============================================================================
format_duration() {
    local seconds=$1
    echo "$((seconds / 60))m $((seconds % 60))s"
}

echo "================================================================================"
echo "Training All Models for Temperature Forecasting"
echo "================================================================================"
echo "Dataset: ${DATASET}"
echo "Models: ${MODELS[@]}"
if [ -n "$SEED" ]; then
    echo "Seed: ${SEED}"
fi
echo "Summary log: ${SUMMARY_LOG}"
echo "Start time: $(date)"
echo "================================================================================"
echo ""

# Initialize summary log
cat > "${SUMMARY_LOG}" <<EOF
===============================================================================
Temperature Forecasting - Training Summary
===============================================================================
Start Time: $(date)
Dataset: ${DATASET}
Models: ${MODELS[@]}
EOF
if [ -n "$SEED" ]; then
    echo "Seed: ${SEED}" >> "${SUMMARY_LOG}"
fi
cat >> "${SUMMARY_LOG}" <<EOF

===============================================================================
EOF

# Train each model
for MODEL in "${MODELS[@]}"; do
    echo -e "${BLUE}================================================================================${NC}"
    echo -e "${BLUE}Training Model: ${MODEL}${NC}"
    echo -e "${BLUE}================================================================================${NC}"
    echo ""
    
    # Record start time
    MODEL_START=$(date +%s)
    MODEL_START_TIME=$(date)
    
    # Create model log file
    if [ -n "$SEED" ]; then
        MODEL_LOG="${MODEL_DIR}/${MODEL}_seed${SEED}_${TIMESTAMP}.log"
    else
        MODEL_LOG="${MODEL_DIR}/${MODEL}_${TIMESTAMP}.log"
    fi
    
    # Build command with optional seed
    # Use -u flag for unbuffered output to see progress in real-time
    if [ -n "$SEED" ]; then
        TRAIN_CMD="python -u -m experiments.run_temperature_prediction dataset=${DATASET} model=${MODEL} seed=${SEED}"
    else
        TRAIN_CMD="python -u -m experiments.run_temperature_prediction dataset=${DATASET} model=${MODEL}"
    fi
    
    # Run training and capture output
    echo -e "${YELLOW}Running: ${TRAIN_CMD}${NC}"
    echo ""
    
    # Run with timeout to prevent infinite hangs (24 hours max per model)
    timeout 86400 bash -c "${TRAIN_CMD}" 2>&1 | tee "${MODEL_LOG}"
    TRAIN_EXIT_CODE=${PIPESTATUS[0]}
    
    if [ $TRAIN_EXIT_CODE -eq 0 ]; then
        # Training succeeded
        MODEL_END=$(date +%s)
        MODEL_DURATION=$((MODEL_END - MODEL_START))
        
        echo ""
        echo -e "${GREEN}✓ ${MODEL} training completed successfully${NC}"
        echo -e "${GREEN}  Duration: $(format_duration ${MODEL_DURATION})${NC}"
        
        # Extract metrics from log
        TEST_MAE=$(grep -oP "test_mae['\"]?\s*[:=]\s*\K[0-9]+\.[0-9]+" "${MODEL_LOG}" | head -1 || echo "N/A")
        TEST_MSE=$(grep -oP "test_mse['\"]?\s*[:=]\s*\K[0-9]+\.[0-9]+" "${MODEL_LOG}" | head -1 || echo "N/A")
        VAL_MAE=$(grep -oP "val_mae['\"]?\s*[:=]\s*\K[0-9]+\.[0-9]+" "${MODEL_LOG}" | tail -1 || echo "N/A")
        BEST_EPOCH=$(grep -oP "best_model_score.*:\s*\K[0-9]+\.[0-9]+" "${MODEL_LOG}" | head -1 || echo "N/A")
        
        # Format duration for logging
        DURATION_STR=$(format_duration ${MODEL_DURATION})
        
        # Log to summary
        cat >> "${SUMMARY_LOG}" <<EOF

-------------------------------------------------------------------------------
Model: ${MODEL}
-------------------------------------------------------------------------------
Status: SUCCESS
Start: ${MODEL_START_TIME}
Duration: ${DURATION_STR}
Best Val MAE: ${VAL_MAE}
Test MAE: ${TEST_MAE}
Test MSE: ${TEST_MSE}
Log file: ${MODEL_LOG}

EOF
        
        echo ""
        echo -e "${GREEN}Metrics:${NC}"
        echo -e "  Val MAE: ${VAL_MAE}"
        echo -e "  Test MAE: ${TEST_MAE}"
        echo -e "  Test MSE: ${TEST_MSE}"
        
    elif [ $TRAIN_EXIT_CODE -eq 124 ]; then
        # Training timed out
        MODEL_END=$(date +%s)
        MODEL_DURATION=$((MODEL_END - MODEL_START))
        DURATION_STR=$(format_duration ${MODEL_DURATION})
        
        echo ""
        echo -e "${RED}✗ ${MODEL} training TIMED OUT (24h limit)${NC}"
        echo -e "${RED}  Duration: ${DURATION_STR}${NC}"
        echo -e "${RED}  Check log: ${MODEL_LOG}${NC}"
        
        # Log to summary
        cat >> "${SUMMARY_LOG}" <<EOF

-------------------------------------------------------------------------------
Model: ${MODEL}
-------------------------------------------------------------------------------
Status: TIMEOUT
Start: ${MODEL_START_TIME}
Duration: ${DURATION_STR}
Error: Training exceeded 24 hour timeout
Log file: ${MODEL_LOG}

EOF
    else
        # Training failed
        MODEL_END=$(date +%s)
        MODEL_DURATION=$((MODEL_END - MODEL_START))
        DURATION_STR=$(format_duration ${MODEL_DURATION})
        
        echo ""
        echo -e "${RED}✗ ${MODEL} training FAILED${NC}"
        echo -e "${RED}  Duration: ${DURATION_STR}${NC}"
        echo -e "${RED}  Exit code: ${TRAIN_EXIT_CODE}${NC}"
        echo -e "${RED}  Check log: ${MODEL_LOG}${NC}"
        
        # Log to summary
        cat >> "${SUMMARY_LOG}" <<EOF

-------------------------------------------------------------------------------
Model: ${MODEL}
-------------------------------------------------------------------------------
Status: FAILED
Start: ${MODEL_START_TIME}
Duration: ${DURATION_STR}
Error: See log file for details
Log file: ${MODEL_LOG}

EOF
    fi
    
    echo ""
done

# Final summary
TOTAL_END=$(date +%s)
echo ""
echo -e "${BLUE}================================================================================${NC}"
echo -e "${BLUE}Training Complete${NC}"
echo -e "${BLUE}================================================================================${NC}"

# Count successes
SUCCESS_COUNT=$(grep -c "Status: SUCCESS" "${SUMMARY_LOG}" || echo "0")
TOTAL_COUNT=${#MODELS[@]}

cat >> "${SUMMARY_LOG}" <<EOF

===============================================================================
Summary
===============================================================================
End Time: $(date)
Models Completed: ${SUCCESS_COUNT}/${TOTAL_COUNT}

EOF

echo ""
echo -e "${GREEN}Results saved to: ${SUMMARY_LOG}${NC}"
echo ""
echo "Model-specific logs:"
for MODEL in "${MODELS[@]}"; do
    if [ -n "$SEED" ]; then
        LOG_FILE="${MODEL_DIR}/${MODEL}_seed${SEED}_${TIMESTAMP}.log"
    else
        LOG_FILE="${MODEL_DIR}/${MODEL}_${TIMESTAMP}.log"
    fi
    if [ -f "${LOG_FILE}" ]; then
        echo "  - ${LOG_FILE}"
    fi
done
echo ""

# Display summary table
echo "================================================================================"
echo "Quick Results Summary"
echo "================================================================================"
printf "%-20s %-10s %-12s %-12s\n" "Model" "Status" "Val MAE" "Test MAE"
echo "--------------------------------------------------------------------------------"

for MODEL in "${MODELS[@]}"; do
    STATUS=$(grep -A 10 "Model: ${MODEL}" "${SUMMARY_LOG}" | grep "Status:" | awk '{print $2}' || echo "UNKNOWN")
    VAL_MAE=$(grep -A 10 "Model: ${MODEL}" "${SUMMARY_LOG}" | grep "Best Val MAE:" | awk '{print $4}' || echo "N/A")
    TEST_MAE=$(grep -A 10 "Model: ${MODEL}" "${SUMMARY_LOG}" | grep "Test MAE:" | awk '{print $3}' || echo "N/A")
    
    if [ "$STATUS" = "SUCCESS" ]; then
        printf "${GREEN}%-20s %-10s %-12s %-12s${NC}\n" "$MODEL" "$STATUS" "$VAL_MAE" "$TEST_MAE"
    else
        printf "${RED}%-20s %-10s %-12s %-12s${NC}\n" "$MODEL" "$STATUS" "$VAL_MAE" "$TEST_MAE"
    fi
done

echo "================================================================================"
echo ""
echo -e "${BLUE}View full summary: cat ${SUMMARY_LOG}${NC}"
echo -e "${BLUE}View MLflow results: mlflow ui --backend-store-uri ./mlruns${NC}"
echo ""

